### PR TITLE
Random target selection and some corrections

### PR DESCRIPTION
**Pull request by abxu**
- Added random target selection (c7f5462)
- Fixed useless reinitialization of listingURL on a lag (b544c1a)
- Fixed a bug when the bot restarts and the progress bar is equal to the hackProgress variable (9f3342e)
- Fixed the position of the github button (24d3880)

### CODE REVIEW

**Comment by snollygolly** [comment]
I have concerns about the way we're doing player targeting in this PR.  At low levels, randomizing the target to attack is totally fine, because it doesn't matter.  As we get up in the ranks, we start to need to target a specific player over and over without randomization (usually because one player is RICH).

In addition to that, #26 was submitted last night and touches on all of these issues.  I've requested changes in that PR, so I'll leave this one open for now (in case the other contributor doesn't fix the requested changes).

Thanks for your contribution!

**Comment by abxu** [comment]
Except that at high level, there are only bots that do the same thing and there is a high probability of not winning the hack when many players are on the same port.
I don't think that the money is important, we earn enough money, when we climb the rankings, to secure the firewalls.

**Comment by snollygolly** [comment]
That's a fair point.  I just know that when I used to use this bot, that was my biggest complaint.  Once I got high enough, it wouldn't stay targeted on the person I wanted.  You're right though, money isn't super important in the late game really.

**Comment by menitol** [comment]
Great! Thanks for fixing this bug. Just one line lol. Imo, the miners are useless for a bot. I disable the miner loop now because I lose more money on a hack and I pay more to hack.

**Comment by menitol** [comment]
Last week, there was a bot called '<:3 )~~~' when I attacked him my 3 ports were hacked instantly. Can you add this feature? It would be really cool.

**Comment by snollygolly** [comment]
@menitol can you put your feature request into an issue?  The PR isn't the right place to discuss it. Thanks!

**Comment by menitol** [comment]
Ok sorry

**Pull request closed without merging**
