### PR TITLE
Added draggable GUI for script

### PR DESCRIPTION
**Pull request by LeeConnelly12**
Added a draggable GUI window for the script.
So far only has stop, restart bot buttons along with Github link.

I think it would be nice to have a GUI to change the word frequency and other options without having to type app.stop() in console and modifying the script.

### CODE REVIEW

**Review by snollygolly — APPROVED** [review]

**Comment by snollygolly** [comment]
This is fantastic!  I think having the word frequency, attacker index, mine frequency, etc. exposed in the GUI would be great.  Great work, and I hope to see more later :shipit:

**Comment by LeeConnelly12** [comment]
Thanks I appreciate it,

gonna be honest though, that draggable function was a snippet from stack
overflow, i tried rewriting it in jquery to keep the consistency but
haven't got anywhere lol.

**Comment by snollygolly** [comment]
I rewrote it to show you what that might look like.  Let me know if you have any questions: https://github.com/snollygolly/sourceio-automation/pull/5

**Comment by LeeConnelly12** [comment]
Yeah that function looks much better now,

looks more like it is part of the script instead of a random snippet.

**Pull request merged**
