### PR TITLE
Pr/26

### PR DESCRIPTION
**Pull request by snollygolly**
This PR aims to resolve feedback addressed in #26 

Full disclosure: I didn't fully test the new miner loop.  I didn't wanna sit there and play the game forever.  If you find an issue with it, lemme know.

### CODE REVIEW

**Review by Ichigo271 — CHANGES_REQUESTED** [review]
Seems good except for the click need arrows, the bot won't upgrade the firewalls if you don't click on one of the firewalls and the arrows works fine even if tutorial is disabled.

**Comment by snollygolly** [comment]
@Ichigo271 I'm not sure what was causing that previously, but during my testing, it works fine now.  No initial click needed. :)

**Comment by Ichigo271** [comment]
@snollygolly Well, i tested it at 19:45 GMT+2 and no initial click, no firewall updates. Not sure why tho.

**Comment by snollygolly** [comment]
How long did you let it run?  Mine didn't click anything for the first 5 mins or so and then started to once it could afford stuff.

**Comment by Ichigo271** [comment]
well i had like 2 quantum servers and 25+ botnets

**Pull request merged**
